version: "3"

volumes:
  pgadmin:
  pgdata:

services:
  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./db:/liquibase/db
      - ./liquibase.properties:/liquibase/liquibase.properties
    depends_on:
      - postgres

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: docker
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres